version: '3.8'

services:
  web:
    build: .
    container_name: my_personal_website
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
